<?php
defined('_EXEC') or die;

/**
* Definimos las extenciones de los ficheros.
*/
define('ADMINISTRATOR', 'administrator');
define('CLASS_PHP', '.class.php');
define('CONTROLLER_PHP', '.controller.php');
define('MODEL_PHP', '.model.php');

/**
* Definimos los directorios de la plataforma.
*/
define('PATH_CONFIGURATION', PATH_ROOT . DIRECTORY_SEPARATOR . 'configuration.php');
define('PATH_COMPONENTS', PATH_ROOT . DIRECTORY_SEPARATOR . 'components' . DIRECTORY_SEPARATOR);
define('PATH_CORE', PATH_ROOT . DIRECTORY_SEPARATOR . 'core' . DIRECTORY_SEPARATOR);
define('PATH_INCLUDES', PATH_ROOT . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR);
define('PATH_LANGUAGE', PATH_ROOT . DIRECTORY_SEPARATOR . 'languages' . DIRECTORY_SEPARATOR);
define('PATH_LAYOUTS', PATH_CORE . 'layouts' . DIRECTORY_SEPARATOR);
define('PATH_LIBRARIES', PATH_ROOT . DIRECTORY_SEPARATOR . 'libraries' . DIRECTORY_SEPARATOR);
define('PATH_BURIPHP_LIBRARIES', PATH_LIBRARIES . 'BuriPHP' . DIRECTORY_SEPARATOR);
define('PATH_UPLOADS', PATH_ROOT . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR);

/**
* Definimos los directorios comunes para vistas html
*/
define('PATH_ASSETS', PATH_ROOT . DIRECTORY_SEPARATOR . 'assets' . DIRECTORY_SEPARATOR);
define('PATH_CSS', PATH_ASSETS . DIRECTORY_SEPARATOR . 'css' . DIRECTORY_SEPARATOR);
define('PATH_FONTS', PATH_ASSETS . DIRECTORY_SEPARATOR . 'fonts' . DIRECTORY_SEPARATOR);
define('PATH_IMAGES', PATH_ASSETS . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR);
define('PATH_JS', PATH_ASSETS . DIRECTORY_SEPARATOR . 'js' . DIRECTORY_SEPARATOR);
define('PATH_PLUGINS', PATH_ROOT . DIRECTORY_SEPARATOR . 'plugins' . DIRECTORY_SEPARATOR);

/**
* Definimos los subdirectorios
*/
define('PATH_CONTROLLERS', PATH_CORE . 'controllers' . DIRECTORY_SEPARATOR);
define('PATH_MODELS', PATH_CORE . 'models' . DIRECTORY_SEPARATOR);

/**
* Definimos los directorios del administrador
*/
define('PATH_ADMINISTRATOR', PATH_ROOT . DIRECTORY_SEPARATOR . ADMINISTRATOR);
define('PATH_ADMINISTRATOR_COMPONENTS', PATH_ADMINISTRATOR . DIRECTORY_SEPARATOR . 'components' . DIRECTORY_SEPARATOR);
define('PATH_ADMINISTRATOR_CORE', PATH_ADMINISTRATOR . DIRECTORY_SEPARATOR . 'core' . DIRECTORY_SEPARATOR);
define('PATH_ADMINISTRATOR_INCLUDES', PATH_ADMINISTRATOR . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR);
define('PATH_ADMINISTRATOR_LANGUAGE', PATH_ADMINISTRATOR . DIRECTORY_SEPARATOR . 'languages' . DIRECTORY_SEPARATOR);
define('PATH_ADMINISTRATOR_LAYOUTS', PATH_ADMINISTRATOR_CORE . 'layouts' . DIRECTORY_SEPARATOR);
define('PATH_ADMINISTRATOR_LIBRARIES', PATH_ADMINISTRATOR . DIRECTORY_SEPARATOR . 'libraries' . DIRECTORY_SEPARATOR);
define('PATH_ADMINISTRATOR_BURIPHP_LIBRARIES', PATH_ADMINISTRATOR_LIBRARIES . 'BuriPHP' . DIRECTORY_SEPARATOR);

/**
* Definimos los directorios comunes del administrador para vistas html
*/
define('PATH_ADMINISTRATOR_ASSETS', PATH_ADMINISTRATOR . DIRECTORY_SEPARATOR . 'css' . DIRECTORY_SEPARATOR);
define('PATH_ADMINISTRATOR_CSS', PATH_ADMINISTRATOR_ASSETS . DIRECTORY_SEPARATOR . 'css' . DIRECTORY_SEPARATOR);
define('PATH_ADMINISTRATOR_FONTS', PATH_ADMINISTRATOR_ASSETS . DIRECTORY_SEPARATOR . 'fonts' . DIRECTORY_SEPARATOR);
define('PATH_ADMINISTRATOR_IMAGES', PATH_ADMINISTRATOR_ASSETS . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR);
define('PATH_ADMINISTRATOR_JS', PATH_ADMINISTRATOR_ASSETS . DIRECTORY_SEPARATOR . 'js' . DIRECTORY_SEPARATOR);
define('PATH_ADMINISTRATOR_PLUGINS', PATH_ADMINISTRATOR . DIRECTORY_SEPARATOR . 'plugins' . DIRECTORY_SEPARATOR);

/**
* Definimos los subdirectorios del administrador
*/
define('PATH_ADMINISTRATOR_CONTROLLERS', PATH_ADMINISTRATOR_CORE . 'controllers' . DIRECTORY_SEPARATOR);
define('PATH_ADMINISTRATOR_MODELS', PATH_ADMINISTRATOR_CORE . 'models' . DIRECTORY_SEPARATOR);

/**
* Definimos el directorio de logs
*/
define('PATH_LOGS', PATH_ROOT . DIRECTORY_SEPARATOR . 'logs' . DIRECTORY_SEPARATOR);
